name: Build Distributions

on:
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NODE_VERSION: 18
  # TODO - set GITHUB_TOKEN for publishing to GitHub

jobs:

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3.3.0

      - name: Set up Node.js ${{ env.NODE_VERSION }} 🔧
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies 🔧
        run: yarn install

      - name: Build 🚀
        run: yarn make

      - name: Upload artifact 📦
        uses: actions/upload-artifact@v3
        with:
          name: linux-dist
          path: ./out/make/zip


  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3.3.0

      - name: Set up Node.js ${{ env.NODE_VERSION }} 🔧
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies 🔧
        run: yarn install

      - name: Build 🚀
        run: yarn make

      - name: Upload artifact 📦
        uses: actions/upload-artifact@v3
        with:
          name: windows-dist
          path: ./out/make/zip/


  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3.3.0

      - name: Set up Node.js ${{ env.NODE_VERSION }} 🔧
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies 🔧
        run: yarn install

      - name: Build 🚀
        run: yarn make

      - name: Upload artifact 📦
        uses: actions/upload-artifact@v3
        with:
          name: macos-dist
          path: ./out/make/zip/darwin
